capston project
Frelly0/My-First-Capstone pull request #1
Opened 2023-07-04 17:46 UTC by Frelly0

Accomplishment 
This my capstone project and during making this project i used many technology which are:

- html
- css
- javaScript

2023-07-04 18:04 UTC, joel-kalema reviewed
Hi @Frelly0 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request  🛑 

![pirates-of-the-caribbean-johnny-depp](https://user-images.githubusercontent.com/57408419/242635897-074a8afb-6646-4281-8ff9-8390f857a9c5.gif)


- [ ] You have submitted a project that doesn't have a descriptive [README](https://github.com/microverseinc/readme-template) 


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @joel-kalema in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-07-04 21:17 UTC, cynthiainga requested changes
Hi @Frelly0, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## Highlights

- [ ] No linters errors ✔️ 
- [ ] The website has the `Home` and `About` pages ✔️ 
- [ ] Correct GitHub flow ✔️ 

## Required Changes ♻️

- [ ] Please kindly check the comments under the review 👇🏾 👇🏾 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-04 21:17 UTC, cynthiainga commented on home.html
> +    </section>
- [ ] Kindly fix the design to match the original design "margin, padding,... 🙃 

Your design

<img width="254" alt="Screenshot 2023-07-04 at 23 55 37" src="https://github.com/Frelly0/My-First-Capstone/assets/74501523/e14573c8-960b-490f-914d-09d89996afbd">

Original design

<img width="216" alt="Screenshot 2023-07-04 at 23 54 51" src="https://github.com/Frelly0/My-First-Capstone/assets/74501523/0f02f6dc-f36d-4708-84cd-c336528d0f4c">

2023-07-04 21:17 UTC, cynthiainga commented on home.html
> +            <img src="./Image/partners/airbnb.png" alt="">
- [ ] All images should contain `alt` attributes `alt="mozilla",...`, kindly fix that 🙏🏾

2023-07-04 21:17 UTC, cynthiainga commented on home.html
> +    </footer>
- [ ] Please kindly make sure you use the same logo everywhere, using two different logos on your web give some confusion. Kindly fix that on the About page as well 🙃 
- [ ] Also kindly customize the text in the footer, this website didn’t talk about creative commons. Kindly fix that on the About page as well 😁 
- [ ] Also the image should contain an `alt` attribute, kindly fix that

2023-07-04 21:17 UTC, cynthiainga commented on about.html
> +            <li class="nav-item"><img src="./Image/twitter.png"></li>
- [ ] All images should contain `alt` attributes `alt="...."`, kindly fix that 🙏🏾

2023-07-04 21:17 UTC, cynthiainga commented on about.html
> +                <img src="./Image/hugging.png">
- [ ] All images should contain `alt` attributes `alt="...."`, kindly fix that 🙏🏾

2023-07-04 21:17 UTC, cynthiainga commented on about.html
> +            <img src="./Image/partners/airbnb.png"/>
- [ ] All images should contain `alt` attributes `alt="...."`, kindly fix that 🙏🏾

2023-07-04 21:17 UTC, cynthiainga commented on README.md
> +This project is under the [Creative Commons Zero v1.0 Universal](./CCO.md) license. Using the design created by [Cindy Shin](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015).
- [ ] The link that you added for the license `Creative Commons Zero v1.0 Universal` is broken please kindly fix that 🙏🏾 

<img width="677" alt="Screenshot 2023-07-04 at 21 54 00" src="https://github.com/Frelly0/My-First-Capstone/assets/74501523/e5fd434f-462e-492c-b2fb-1e506039fba5">

2023-07-05 12:12 UTC, iambenkis requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @Frelly0 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 

- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me @iambenkis  when you comment, so I can receive the notification or use Slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-05 21:13 UTC, algerina approved these changes
Hi @Frelly0 ,

Great job so far!  

May I highlight the following: 
- [x] Your  project looks good👏  ✔️ 
- [x] You implemented the requirements of the previous TSE✔️ 

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:

Your project is complete!  It's time to merge it :shipit:

<img src="https://media4.giphy.com/media/tIeCLkB8geYtW/giphy.gif"/>

 
 ## Optional suggestions

 - Please check the comment under the review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread and tag me @algerina if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [Algerina](https://github.com/algerina), I will receive a notification and will respond._

[GitHub](https://github.com/algerina) | [LinkedIn](https://linkedin.com/in/amel-khiri) | [Twitter](https://twitter.com/AmelQahwadji)

2023-07-06 06:45 UTC, merged